org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

systemProp.net.minecraftforge.gradle.repo.recompile.fork=true
systemProp.net.minecraftforge.gradle.repo.recompile.fork.args=-Xmx5G

systemProp.net.minecraftforge.gradle.repo.attach=false

minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
forge_version=61.0.10
forge_version_range=[0,)
loader_version_range=[0,)
mapping_channel=parchment
mapping_version=2025.12.20-1.21.11

mod_id=tabakmod
mod_name=Super Tabakmod
mod_license=All Rights Reserved
mod_version=3.1-1.21.11
mod_group_id=mett.palemannie.tabakmod
mod_authors=Quake 1 Ranger Man (Manfred_Blasser||Pale Mannie), KnocksSchiller
mod_description=Feinste Marlborower Tabakwaren